package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COUNTRY.
 */
public class Country {

    private Long order;
    private String code;
    private String slug;
    private String name;

    public Country() {
    }

    public Country(String code) {
        this.code = code;
    }

    public Country(Long order, String code, String slug, String name) {
        this.order = order;
        this.code = code;
        this.slug = slug;
        this.name = name;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
