package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Dormitory;
import greendao.Category;
import greendao.Country;
import greendao.Validate;

import greendao.DormitoryDao;
import greendao.CategoryDao;
import greendao.CountryDao;
import greendao.ValidateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dormitoryDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig validateDaoConfig;

    private final DormitoryDao dormitoryDao;
    private final CategoryDao categoryDao;
    private final CountryDao countryDao;
    private final ValidateDao validateDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dormitoryDaoConfig = daoConfigMap.get(DormitoryDao.class).clone();
        dormitoryDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        validateDaoConfig = daoConfigMap.get(ValidateDao.class).clone();
        validateDaoConfig.initIdentityScope(type);

        dormitoryDao = new DormitoryDao(dormitoryDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        validateDao = new ValidateDao(validateDaoConfig, this);

        registerDao(Dormitory.class, dormitoryDao);
        registerDao(Category.class, categoryDao);
        registerDao(Country.class, countryDao);
        registerDao(Validate.class, validateDao);
    }
    
    public void clear() {
        dormitoryDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        countryDaoConfig.getIdentityScope().clear();
        validateDaoConfig.getIdentityScope().clear();
    }

    public DormitoryDao getDormitoryDao() {
        return dormitoryDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public ValidateDao getValidateDao() {
        return validateDao;
    }

}
