package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VALIDATE.
 */
public class Validate {

    private Long worker_id;
    private Integer count;
    private Long time;

    public Validate() {
    }

    public Validate(Long worker_id) {
        this.worker_id = worker_id;
    }

    public Validate(Long worker_id, Integer count, Long time) {
        this.worker_id = worker_id;
        this.count = count;
        this.time = time;
    }

    public Long getWorker_id() {
        return worker_id;
    }

    public void setWorker_id(Long worker_id) {
        this.worker_id = worker_id;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
